add_newline = false

[git_status]
disabled = true

[git_branch]
symbol = "🌱 "

# Disable visual noise "via <language xyz>..."
[package]
disabled = true
[aws]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[rust]
disabled = true
[java]
disabled = true
[ruby]
disabled = true
[golang]
disabled = true

[character]
format = """
[➜ ](bold green) """
